experiment: huawei_sep_kan_ir
save_dir: experiments
resume: True

model:
  type: sr_kan
  params:
    encoder: unet
    in_dims:
      - 3
    out_dims:
      - 3
    kernel_sizes:
      - 3
    grid_size: 5
    spline_order: 3
    residual_std: 0.1
    grid_range:
      - 0.0
      - 1.0

data:
  type: huawei_img
  train:
    source: 'data/huawei/train/source'
    target: 'data/huawei/train/target'
  val:
    source: 'data/huawei/val/source'
    target: 'data/huawei/val/target'
  test:
    source: 'data/huawei/test/source'
    target: 'data/huawei/test/target'

pipeline:
  type: sr_kan
  params:
    lr: 1e-3
    batch_size: 2
    val_batch_size: 2
    test_batch_size: 2
    epochs: 600
    save_freq: 10
    visualize_freq: 10
